### ISSUE TITLE
bbswitch and kernel 4.15.10

### ISSUE THREAD

**Issue by kmare** [gsgatlin/optimus-rpms#3]
Updating to kernel 4.15.10 from 4.15.9, bbswitch doesn't work anymore. Check for the file in /usr/lib/modules/4.15.10-300.fc27.x86_64/extra and apparently there is only bbswitch.ko.xz and not bbswitch.ko as it should. With previews kernels it was working fine. Is it a bug with the new kernel?

I uncompressed the file and tried to modprobe the module, but I get the following error:
modprobe: ERROR: could not insert 'bbswitch': Unknown symbol in module, or unknown parameter (see dmesg)

**Comment by gsgatlin** [comment]
Hello. I upgraded my kernel this morning and bbswitch is working ok on one of my laptops. I did not have a chance to check the other one yet.

```
[gsgatlin@t540p ~]$ uname -a
Linux t540p.eos.ncsu.edu 4.15.10-300.fc27.x86_64 #1 SMP Thu Mar 15 17:13:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[gsgatlin@t540p ~]$ cat /proc/acpi/bbswitch 
0000:01:00.0 OFF
```
I wonder if something got messed up in the dkms process?

There are a couple of things that could be tried.

```
dkms remove -m bbswitch -v 0.8.0 --all
dkms add -m bbswitch -v 0.8.0
dkms build -m bbswitch -v 0.8.0
dkms install -m bbswitch -v 0.8.0
```
If that doesn't help, maybe you could try removing and adding back the rpm? Like this:

```
rpm -e --nodeps bbswitch-dkms
yum install bbswitch-dkms
```

I just tested it on my laptop with
```
optirun -b primus glxgears -info
```
And the /proc/acpi/bbswitch file switched from off to on and then off again once I closed the glxgears window.

**Comment by kmare** [comment]
Thank you so much for the detailed answer, I'll keep it in mind for next time (hopefully won't need to). Apparently after manually uncompressing the module, signing it (secure boot), rebooting a couple of times and finally manually inserting it, it worked.

**Comment by kmare** [comment]
Just as a follow up updating to 4.15.12-301.fc27.x86_64. I had problems again updating as there was only a bbswitch.ko.xz module. As you suggested, I tried with 
``dkms remove -m bbswitch -v 0.8.0 --all``
``dkms add -m bbswitch -v 0.8.0``
``dkms build -m bbswitch -v 0.8.0``
``dkms install -m bbswitch -v 0.8.0``
and it finally worked!

Thank you again!
