### ISSUE TITLE
Kernel 4.16.3

### ISSUE THREAD

**Issue by kmare** [gsgatlin/optimus-rpms#4]
Just upgrade to the fedora kernel 4.16.3-200.fc27.x86_64. Apparently I can't load the nvidia driver. I keep getting the following error:
[user@penguin ~] $ primusrun glxinfo -B
primus: fatal: Bumblebee daemon reported: error: Could not load GPU driver

and:
[user@penguin ~] $ optirun -b primus glxgears -info
[  566.429683] [ERROR]Cannot access secondary GPU - error: Could not load GPU driver

[  566.429716] [ERROR]Aborting because fallback start is disabled.

EDIT:
ok so checked dmesg and I got these errors:
[  232.339857] nvidia: Unknown symbol swiotlb_map_sg_attrs (err 0)
[  290.352607] nvidia: Unknown symbol swiotlb_map_sg_attrs (err 0)
[  438.360216] nvidia: Unknown symbol swiotlb_map_sg_attrs (err 0)
[  567.016941] nvidia: Unknown symbol swiotlb_map_sg_attrs (err 0)

EDIT 2:
it's a known problem. There are patches here:
https://devtalk.nvidia.com/default/topic/1030082/linux/kernel-4-16-rc1-breaks-latest-drivers-unknown-symbol-swiotlb_map_sg_attrs-/

**Comment by gsgatlin** [comment]
Yeah. Looks like I need to add the patch. will work on that asap.

**Comment by gsgatlin** [comment]
Tested patched rpm with 4.15.17-300.fc27.x86_64 and it works ok. So it should be safe for fedora 26. Also it was super easy since I did not need to modify the patch at all. Updating my kernel to 4.16.3-200.fc27 and rebooting to test to see if the patch works on newer kernel.

**Comment by gsgatlin** [comment]
I think you should be able to dnf update to 390.48-2 now. Might have to clean the cache.

**Comment by kmare** [comment]
Just updated, and it works great! Thanks for the quick fix, it's really appreciated!
