### ISSUE TITLE
Fedora 28 support

### ISSUE THREAD

**Issue by smekras** [gsgatlin/optimus-rpms#5]
When could we expect support for Fedora 28? I plan to update to it soon, and I'd like to know it will be supported. Your repo is what I seem to need.

Thanks in advance.

**Comment by gsgatlin** [comment]
Everything works except for VirtualGL.

I am working on an update to VirtualGL to 2.5.2. I have (mostly) fixed the paths to be moved out of /opt. I have to move the libfaker library, and remove the bundled libraries. I will report back when I have something ready to test. If you use primus bridge then nothing further is needed to use it now.

https://bugzilla.redhat.com/show_bug.cgi?id=1566666

**Comment by smekras** [comment]
Thanks for the swift response.

Also, I have noticed that the latest nvidia driver is missing from
http://install.linux.ncsu.edu/pub/yum/itecs/public/bumblebee-nonfree/fedora28/x86_64/
Are you going to update the managed nvidia driver as well?

**Comment by gsgatlin** [comment]
Yeah. I'll try to update that today.

**Comment by gsgatlin** [comment]
Doh. Sorry. Yeah, don't look in that yum repo. Its kind of dead. :)

You want:

https://linux.itecs.ncsu.edu/redhat/public/bumblebee-nonfree/fedora28/x86_64/

Had to stop using that other URL because the servers its using are unreliable.

Sadly, the manager who's staff runs http://install.linux.ncsu.edu/ has stopped replying to my emails. :(

**Comment by gsgatlin** [comment]
Here is a link to some documentation I wrote:

https://www.linux.ncsu.edu/bumblebee

It has the new URLs in it.

Also, the "release" rpms at http://install.linux.ncsu.edu/ when dnf updated re points to the newer yum repo. So the driver is up to date as of today. I will continue working on VirtualGL this morning as time permits. I am in meetings all afternoon. It may take a few days to get it all sorted out.

**Comment by kmare** [comment]
Hi @gsgatlin , thank you for your dedication! Did you get to sort out VirtualGL? Plan to update some laptops to Fedora 28 and I'd like to first know that your repo is working fine.

**Comment by gsgatlin** [comment]
So its not fixed yet.

I am working on it today. At first I tried to use DRC's rpm and make it more fedora like. But I have given up on that even though it was working.

At this point, I am trying to fix the fedora rpm and submit it as a update to fedora.

The VirtualGL-glx.patch has been re-done for VirtualGL 2.5.2. And it gets 100% of the way through the compile now after redoing that one.Next problem to solve in rpmbuild is

ln: failed to create symbolic link '/home/gsgatlin/redhat/BUILDROOT/VirtualGL-2.5.2-11.fc28.x86_64/usr/lib64/fakelib/libGL.so': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.qE4Ndv (%install)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.qE4Ndv (%install)


So I will keep working on it. I'll let you know when I have it fixed. Sorry for the delay.

**Comment by kmare** [comment]
Please, no need to be sorry! Your work is really appreciated, take your time. And thank you for reporting back about the progress and status.

**Comment by gsgatlin** [comment]
Got something that works with optimus laptop (optirun) in fedora 28 after more work today. So tonight I will make a RHEL 6 ppc vm in qemu to make sure it builds there ok and to see if VirtualGL-gccrhel6fix.patch is still needed. (hopefully not) Then I just need 2 patches which I think are done now.

Tomorrow I will test vglconnect / vglrun on two PCs, the server, a DELL desktop with nvidia card, and the client, a fedora 28 laptop with Intel GPU. If that works I will submit VirtualGL package as an update and simultaneously close out the various bugzilla reports. Feel like I'm a lot closer now to having something ready.

**Comment by gsgatlin** [comment]
I have sent an email to legal@lists.fedoraproject.org asking if the change of license from "wxWidgets" to "wxWindows Library License v3.1" in the new version is permitted to be in fedora/EPEL. I have something that builds now but more tests need to be done with vglconnect / vglrun before submitting it as an update.

**Comment by gsgatlin** [comment]
Its working good with fedora 28 to fedora 28 with vglrun. I will test fedora 28 to centos 6/7 server when I get back from a trip I have to take to D.C. in the next 3 days.

**Comment by gsgatlin** [comment]
Ok. VirtualGL package submitted as update. Its been submitted to updates-testing.

https://fedoraproject.org/wiki/How_to_test_updates

When there is enough karma and I am allowed I will push out an update to f28, f27, epel7, epel6. Thanks.

**Comment by kmare** [comment]
Thank you so much, I'll try and update as soon as I can.

**Comment by gsgatlin** [comment]
This should be fixed. Forgot to close this.
